<script>
  //LIBS

  //CONTAINERS
  import SectionContainer from "../../containers/section-two-cols.svelte";
</script>

<SectionContainer>
  <div
    class="flex items-center w-full text-on-background-variant text-4xl leading-5xl text-left"
  >
    <h1>
      Most of the used oil generated in the refining process is adding to world
      pollution.
    </h1>
  </div>
  <div
    class="flex items-center w-full text-on-background-variant text-lg text-left"
  >
    <h1>
      Approximately 1.3 billion gallons of used oil per year are generated by
      the automotive and industrial sectors for collection and re-use in the
      united states alone and only close to 330 million are processed into
      recycled oil or fuel, <span class="text-primary-light font-bold underline"
        >we are here to close this GAP!</span
      >
    </h1>
  </div>
</SectionContainer>

<style>
  * {
    overflow: hidden;
  }
</style>
